version: '3.5'

volumes:
  rinhadb:

networks:
  default:
    driver: bridge
    name: rinhaWeb

services:

  postgresql:
    image: "postgres:latest"
    hostname: postgresql
    volumes:
      - ./Database/Create.sql:/docker-entrypoint-initdb.d/Create.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rinha
    command: postgres -c 'max_connections=450'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '1.5GB'
  
  api1:
    build:
      context: .
      dockerfile: dockerfile
    hostname: api1
    depends_on:
      - postgresql
      - redis
    environment:
      - DB_CONNECTION_STRING=Host=postgresql;Username=root;Password=root;Database=rinha;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true;MinPoolSize=1;MaxPoolSize=1024;
      - REDIS_CONNECTION_STRING=redis
      - ASPNETCORE_URLS=http://+:3000;http://+:3001
      - DOTNET_TieredPGO=1
      - DOTNET_ReadyToRun=0
      - DOTNET_TC_QuickJitForLoops=1
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2:
    build:
      context: .
      dockerfile: dockerfile
    hostname: api2
    depends_on:
      - postgresql
      - redis
    environment:
      - DB_CONNECTION_STRING=Host=postgresql;Username=root;Password=root;Database=rinha;Connection Pruning Interval=1;Connection Idle Lifetime=2;Enlist=false;No Reset On Close=true;MinPoolSize=1;MaxPoolSize=1024;
      - REDIS_CONNECTION_STRING=redis
      - ASPNETCORE_URLS=http://+:3000;http://+:3001
      - DOTNET_TieredPGO=1
      - DOTNET_ReadyToRun=0
      - DOTNET_TC_QuickJitForLoops=1
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  
  nginx:
    image: "nginx:latest"
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - api1
      - api2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '0.4GB'

  redis:
    image: 'redis:latest'
    hostname: redis
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.1GB'