CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS PESSOA(
    ID UUID PRIMARY KEY,
    APELIDO VARCHAR(32) UNIQUE NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    STACK VARCHAR(320),
    BUSCA VARCHAR(360) GENERATED ALWAYS AS (
        LOWER(NOME || ' ' || APELIDO || ' ' || STACK)
        ) STORED
    );

CREATE INDEX pessoa_busca_idx ON PESSOA USING GIST (BUSCA gist_trgm_ops);